### ISSUE TITLE
相似度

### ISSUE THREAD

**Issue by 469065768** [xdyuchen/AudioScore#1]
请问FFT项目里面有什么功能，相似度余弦会不会太粗糙，考虑加入其它评测因子

**Comment by xdyuchen** [comment]
很早前练手的项目，很粗糙的代码

**Comment by 469065768** [comment]
有没计划做得深入一些，因为这种音频对鄙视可以做离线，而且有速度优势，感觉训练的准确度也不够

**Comment by xdyuchen** [comment]
暂时没有计划哦，感觉这个方式不适用于运用，这个算法对录音数据要求在时间序列上能完全对应才有效，实际运用误差会很大
